all:sigcat hq
sigcat: sigcat.c
	gcc -og  -pedantic -Wall -std=gnu99 -I/local/courses/csse2310/include -L/local/courses/csse2310/lib -lcsse2310a3 -o sigcat sigcat.c
hq:hq.c
	gcc -og  -pedantic -Wall -std=gnu99 -I/local/courses/csse2310/include -L/local/courses/csse2310/lib -lcsse2310a3 -o hq hq.c
